;this file for FamiTone2 libary generated by text2data tool

after_the_rain_music_data:
.scope
	.byte 1
	.word _instruments
	.word _samples-4
	.word _song0ch0,_song0ch1,_song0ch2,_song0ch3,_song0ch4,307,256

_instruments:
	.byte $30 ;instrument $00
	.word _env1,_env16,_env0
	.byte $00
	.byte $70 ;instrument $01
	.word _env2,_env0,_env17
	.byte $00
	.byte $70 ;instrument $02
	.word _env3,_env14,_env0
	.byte $00
	.byte $70 ;instrument $03
	.word _env3,_env15,_env0
	.byte $00
	.byte $30 ;instrument $04
	.word _env4,_env0,_env0
	.byte $00
	.byte $70 ;instrument $05
	.word _env5,_env14,_env0
	.byte $00
	.byte $70 ;instrument $06
	.word _env5,_env15,_env0
	.byte $00
	.byte $30 ;instrument $07
	.word _env6,_env0,_env0
	.byte $00
	.byte $30 ;instrument $08
	.word _env7,_env0,_env0
	.byte $00
	.byte $b0 ;instrument $09
	.word _env10,_env0,_env0
	.byte $00
	.byte $30 ;instrument $0a
	.word _env5,_env0,_env0
	.byte $00
	.byte $70 ;instrument $0b
	.word _env9,_env0,_env17
	.byte $00
	.byte $30 ;instrument $0c
	.word _env1,_env0,_env0
	.byte $00
	.byte $b0 ;instrument $0d
	.word _env2,_env0,_env17
	.byte $00
	.byte $b0 ;instrument $0e
	.word _env9,_env0,_env0
	.byte $00
	.byte $30 ;instrument $0f
	.word _env11,_env16,_env0
	.byte $00
	.byte $30 ;instrument $10
	.word _env12,_env0,_env17
	.byte $00
	.byte $30 ;instrument $11
	.word _env9,_env0,_env0
	.byte $00
	.byte $70 ;instrument $12
	.word _env13,_env0,_env17
	.byte $00

_samples:
	.byte $00+FT_DPCM_PTR,$0c,$0f,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $04+FT_DPCM_PTR,$1b,$0f,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $0b+FT_DPCM_PTR,$22,$0f,$00
	.byte $14+FT_DPCM_PTR,$0d,$0f,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $18+FT_DPCM_PTR,$0a,$0f,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $00+FT_DPCM_PTR,$00,$00,$00
	.byte $1b+FT_DPCM_PTR,$36,$0f,$00

_env0:
	.byte $c0,$00,$00
_env1:
	.byte $cf,$00,$00
_env2:
	.byte $c5,$c6,$c7,$05,$c6,$0b,$c5,$0f,$c4,$11,$c3,$14,$c2,$15,$c1,$1d
	.byte $c0,$00,$10
_env3:
	.byte $c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0a
_env4:
	.byte $c8,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$07
_env5:
	.byte $c3,$02,$c2,$02,$c1,$02,$c0,$00,$06
_env6:
	.byte $ca,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$0b
_env7:
	.byte $c6,$c6,$c3,$03,$c2,$03,$c1,$c1,$c0,$00,$08
_env8:
	.byte $c1,$c2,$c3,$03,$c2,$02,$c1,$02,$c0,$00,$08
_env9:
	.byte $c4,$03,$c3,$03,$c2,$30,$c1,$45,$c0,$00,$08
_env10:
	.byte $c8,$c5,$c5,$c4,$c4,$c3,$00,$05
_env11:
	.byte $cf,$cf,$c0,$00,$02
_env12:
	.byte $c9,$06,$c8,$08,$c7,$08,$c6,$09,$c5,$0a,$c4,$0e,$c3,$11,$c2,$16
	.byte $c1,$18,$c0,$00,$12
_env13:
	.byte $c5,$03,$c4,$06,$c3,$09,$c2,$23,$c3,$0a,$c4,$11,$c3,$0d,$c2,$0a
	.byte $c1,$0f,$c0,$00,$12
_env14:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
_env15:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
_env16:
	.byte $cc,$c0,$00,$01
_env17:
	.byte $c0,$0f,$c1,$c0,$c1,$c0,$bf,$c0,$bf,$c0,$00,$01
_env18:
	.byte $c8,$c2,$c2,$c2,$00,$03


_song0ch0:
_song0ch0loop:
_ref0:
	.byte $84,$41,$41,$41,$8a,$41,$84,$41,$8a,$41,$41,$84,$41,$41,$41,$41
	.byte $8a,$41,$84,$41,$8a,$41,$84,$41,$40,$81
_ref1:
	.byte $86,$47,$47,$47,$8c,$47,$86,$47,$8c,$47,$47,$86,$47,$47,$47,$47
	.byte $8c,$47,$86,$47,$8c,$47,$86,$47,$46,$81
_ref2:
	.byte $39,$39,$39,$8c,$39,$86,$39,$8c,$39,$39,$86,$39,$39,$39,$39,$8c
	.byte $39,$86,$39,$8c,$39,$86,$39,$38,$81
_ref3:
	.byte $3d,$3d,$3d,$8c,$3d,$86,$3d,$8c,$3d,$3d,$86,$3d,$3d,$3d,$3d,$8c
	.byte $3d,$86,$3d,$8c,$3d,$3c,$85
	.byte $ff,$11
	.word _ref0
	.byte $ff,$11
	.word _ref1
	.byte $ff,$11
	.word _ref2
_ref7:
	.byte $3d,$3d,$3d,$8c,$3d,$86,$3d,$8c,$3d,$86,$3d,$3d,$3d,$3d,$8c,$3d
	.byte $3c,$91
_ref8:
	.byte $87,$84,$41,$41,$8a,$40,$85,$84,$41,$8a,$41,$96,$24,$28,$83,$84
	.byte $41,$41,$8a,$41,$96,$2f,$84,$41,$8a,$40,$81
_ref9:
	.byte $96,$2c,$2e,$83,$86,$47,$47,$8c,$47,$96,$2f,$86,$47,$8c,$47,$96
	.byte $2c,$85,$86,$47,$47,$8c,$46,$85,$96,$1e,$85
_ref10:
	.byte $20,$85,$86,$39,$39,$8c,$39,$96,$21,$86,$39,$8c,$38,$89,$86,$39
	.byte $39,$8c,$38,$85,$86,$39,$8c,$38,$81
_ref11:
	.byte $96,$36,$85,$86,$3d,$3d,$8c,$3c,$85,$86,$3d,$8c,$3d,$96,$32,$85
	.byte $86,$3d,$3d,$8c,$3c,$8d
	.byte $ff,$11
	.word _ref8
_ref13:
	.byte $96,$2c,$2e,$83,$86,$47,$47,$8c,$47,$96,$2f,$86,$47,$8c,$47,$96
	.byte $32,$85,$86,$47,$47,$8c,$46,$85,$96,$36,$85
_ref14:
	.byte $38,$85,$86,$39,$39,$8c,$38,$85,$86,$39,$8c,$38,$89,$86,$39,$39
	.byte $8c,$38,$85,$86,$39,$8c,$38,$81
_ref15:
	.byte $96,$3c,$85,$86,$3d,$3d,$8c,$3c,$85,$86,$3d,$8c,$3c,$89,$86,$3d
	.byte $3d,$8c,$3c,$85,$86,$3d,$8c,$3c,$81
_ref16:
	.byte $96,$21,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$39,$9c,$3d
	.byte $86,$39,$9c,$38,$85,$86,$39,$39,$9c,$36,$85
_ref17:
	.byte $96,$33,$86,$3d,$3d,$9c,$25,$86,$3d,$8c,$3d,$86,$3d,$3d,$8c,$3d
	.byte $86,$3d,$9c,$32,$85,$86,$3d,$3d,$9c,$2c,$85
_ref18:
	.byte $83,$86,$2f,$2f,$9c,$37,$86,$2f,$9c,$37,$86,$2f,$2f,$9c,$37,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$9c,$2c,$2e,$83
_ref19:
	.byte $33,$84,$29,$29,$9c,$33,$84,$29,$8a,$29,$84,$29,$29,$9c,$2f,$84
	.byte $29,$9c,$2e,$85,$84,$29,$29,$8a,$28,$85
_ref20:
	.byte $83,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$38,$85,$39,$9c
	.byte $2c,$85,$86,$39,$39,$9c,$32,$85
_ref21:
	.byte $2c,$2e,$86,$3d,$3d,$9c,$2f,$86,$3d,$8c,$3d,$86,$3d,$3d,$9c,$2d
	.byte $86,$3d,$9c,$2c,$85,$86,$3d,$3d,$8c,$3c,$85
_ref22:
	.byte $83,$86,$2f,$2f,$9c,$3d,$86,$2f,$9c,$3d,$86,$2f,$2f,$8c,$2f,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$9c,$46,$85
_ref23:
	.byte $4b,$86,$2f,$2f,$9c,$4b,$86,$2f,$8c,$2f,$86,$2f,$2f,$9c,$46,$8d
	.byte $96,$2c,$2e,$83,$32,$85
_ref24:
	.byte $21,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$39,$9c,$3d,$86
	.byte $39,$9c,$38,$85,$86,$39,$39,$9c,$36,$85
	.byte $ff,$10
	.word _ref17
	.byte $ff,$11
	.word _ref18
	.byte $ff,$10
	.word _ref19
_ref28:
	.byte $83,$86,$39,$39,$9c,$21,$86,$39,$9c,$25,$86,$39,$39,$8c,$39,$86
	.byte $39,$8c,$38,$85,$86,$39,$38,$9c,$26,$28,$85
_ref29:
	.byte $2d,$86,$3d,$3d,$9c,$29,$86,$3d,$9c,$2d,$86,$3d,$3d,$8c,$3d,$86
	.byte $3d,$8c,$3c,$85,$86,$3d,$3c,$9c,$2c,$2e,$85
_ref30:
	.byte $33,$86,$2f,$2f,$9c,$2f,$86,$2f,$9c,$2f,$86,$2f,$2f,$9c,$2f,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$8c,$2e,$85
_ref31:
	.byte $83,$86,$2f,$2f,$8c,$2f,$86,$2f,$8c,$2f,$86,$2f,$2f,$8c,$2e,$9d
	.byte $ff,$11
	.word _ref0
	.byte $ff,$11
	.word _ref1
	.byte $ff,$11
	.word _ref2
	.byte $ff,$10
	.word _ref3
	.byte $ff,$11
	.word _ref0
	.byte $ff,$11
	.word _ref1
	.byte $ff,$11
	.word _ref2
	.byte $ff,$0d
	.word _ref7
_ref40:
	.byte $8f,$9a,$36,$85,$3a,$3c,$8b,$3a,$85,$36,$85,$28,$85
_ref41:
	.byte $9f,$44,$85,$46,$95
_ref42:
	.byte $8f,$36,$85,$3a,$3c,$8b,$3a,$85,$28,$85,$2c,$85
_ref43:
	.byte $8f,$2d,$2f,$2c,$a5
_ref44:
	.byte $8f,$36,$85,$3a,$3c,$8b,$3a,$85,$32,$85,$36,$85
	.byte $ff,$05
	.word _ref41
_ref46:
	.byte $8f,$4e,$85,$4a,$8d,$46,$85,$44,$85,$40,$44,$83
_ref47:
	.byte $8f,$45,$47,$4a,$8d,$46,$85,$44,$8d
_ref48:
	.byte $8f,$a0,$10,$14,$83,$16,$8d,$16,$85,$14,$85,$16,$85
_ref49:
	.byte $9f,$14,$16,$83,$1a,$85,$1e,$8d
_ref50:
	.byte $16,$a5,$10,$14,$83,$16,$85,$14,$85
_ref51:
	.byte $87,$28,$2c,$83,$2e,$85,$2c,$8d,$82,$28,$2c,$83,$2e,$85,$2c,$85
_ref52:
	.byte $8f,$a0,$28,$2c,$83,$2e,$8d,$2c,$85,$28,$85,$2e,$85
_ref53:
	.byte $8f,$82,$2c,$2e,$83,$32,$85,$a0,$2c,$2e,$83,$32,$85,$36,$8d
_ref54:
	.byte $38,$ad,$36,$38,$83,$3c,$85
_ref55:
	.byte $87,$3a,$3c,$87,$3a,$3c,$83,$a2,$3d,$a0,$3c,$9d
	.byte $ff,$10
	.word _ref16
	.byte $ff,$10
	.word _ref17
	.byte $ff,$11
	.word _ref18
	.byte $ff,$10
	.word _ref19
	.byte $ff,$10
	.word _ref20
	.byte $ff,$11
	.word _ref21
	.byte $ff,$10
	.word _ref22
	.byte $ff,$0f
	.word _ref23
	.byte $ff,$10
	.word _ref24
	.byte $ff,$10
	.word _ref17
	.byte $ff,$11
	.word _ref18
	.byte $ff,$10
	.word _ref19
	.byte $ff,$11
	.word _ref28
	.byte $ff,$11
	.word _ref29
	.byte $ff,$10
	.word _ref30
	.byte $ff,$0a
	.word _ref31
	.byte $fd
	.word _song0ch0loop

_song0ch1:
_song0ch1loop:
_ref72:
	.byte $92,$11,$11,$11,$94,$11,$92,$29,$11,$94,$29,$92,$0d,$11,$11,$11
	.byte $94,$11,$92,$29,$2d,$94,$29,$92,$2e,$81
_ref73:
	.byte $94,$2f,$92,$17,$17,$94,$17,$92,$2f,$17,$94,$2f,$92,$11,$17,$17
	.byte $17,$94,$17,$92,$2f,$94,$2f,$92,$2c,$2e,$2c,$81
_ref74:
	.byte $09,$09,$09,$94,$09,$92,$21,$09,$94,$21,$92,$07,$09,$09,$09,$94
	.byte $09,$92,$21,$23,$94,$21,$92,$24,$81
_ref75:
	.byte $94,$25,$92,$0d,$0d,$94,$0d,$92,$25,$0d,$94,$25,$92,$0b,$0d,$94
	.byte $0b,$92,$25,$2d,$2f,$94,$2d,$92,$2c,$2e,$2c,$81
_ref76:
	.byte $11,$11,$11,$94,$11,$92,$29,$11,$94,$29,$92,$0d,$11,$11,$11,$94
	.byte $11,$92,$29,$2d,$94,$29,$92,$2e,$81
	.byte $ff,$12
	.word _ref73
	.byte $ff,$11
	.word _ref74
_ref79:
	.byte $94,$25,$92,$0d,$0d,$94,$0d,$92,$22,$24,$0d,$2c,$2e,$2d,$24,$85
	.byte $94,$24,$85,$92,$0d,$94,$0d,$92,$25,$24,$81
_ref80:
	.byte $11,$94,$10,$91,$82,$24,$28,$83,$2c,$85,$2e,$85,$32,$85,$2c,$2e
	.byte $83
_ref81:
	.byte $97,$2c,$95,$1e,$85,$20,$85
_ref82:
	.byte $af,$36,$38,$83,$36,$85
_ref83:
	.byte $97,$32,$a5
_ref84:
	.byte $97,$24,$28,$83,$2c,$85,$2e,$85,$32,$85,$2c,$2e,$83
_ref85:
	.byte $97,$32,$95,$36,$85,$38,$85
_ref86:
	.byte $af,$36,$38,$83,$3c,$85
_ref87:
	.byte $bf
_ref88:
	.byte $8f,$9a,$38,$9c,$39,$9a,$38,$3d,$38,$91,$36,$85,$32,$85
_ref89:
	.byte $24,$95,$2d,$9c,$2d,$9a,$2e,$32,$83,$2e,$85,$2c,$8d
_ref90:
	.byte $36,$a5,$33,$9c,$33,$9a,$2c,$2e,$83,$32,$85
_ref91:
	.byte $97,$2e,$a5
_ref92:
	.byte $97,$28,$9c,$29,$9a,$28,$2c,$85,$2e,$85,$32,$83,$2c,$2e,$85
_ref93:
	.byte $97,$2c,$a5
_ref94:
	.byte $3c,$a5,$3c,$85,$46,$85,$4a,$85
_ref95:
	.byte $97,$46,$a5
_ref96:
	.byte $8f,$38,$9c,$39,$9a,$38,$3d,$38,$91,$36,$85,$32,$85
	.byte $ff,$0b
	.word _ref89
	.byte $ff,$09
	.word _ref90
_ref99:
	.byte $97,$2e,$a5
_ref100:
	.byte $1e,$20,$87,$24,$89,$29,$9c,$29,$9a,$24,$8b,$26,$28,$85,$2c,$85
_ref101:
	.byte $28,$89,$2c,$89,$2f,$9c,$2f,$9a,$2c,$8b,$2c,$2e,$85,$32,$85
_ref102:
	.byte $2e,$bd
_ref103:
	.byte $a4,$14,$16,$bb
	.byte $ff,$11
	.word _ref72
	.byte $ff,$12
	.word _ref73
	.byte $ff,$11
	.word _ref74
	.byte $ff,$12
	.word _ref75
	.byte $ff,$11
	.word _ref76
	.byte $ff,$12
	.word _ref73
	.byte $ff,$11
	.word _ref74
	.byte $ff,$13
	.word _ref79
_ref112:
	.byte $11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$29,$9c,$3a,$3c
	.byte $83,$84,$29,$29,$8a,$29,$9c,$3b,$92,$29,$94,$28,$81
_ref113:
	.byte $92,$11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$28,$89,$92
	.byte $11,$94,$11,$92,$29,$94,$29,$92,$2f,$94,$2e,$81
_ref114:
	.byte $92,$17,$94,$17,$86,$2f,$2f,$8c,$2e,$85,$86,$2f,$8c,$2f,$9c,$3a
	.byte $3c,$83,$86,$2f,$2f,$8c,$2f,$9c,$3b,$92,$2f,$94,$2e,$81
_ref115:
	.byte $92,$0d,$94,$0d,$86,$25,$25,$8c,$24,$85,$86,$25,$8c,$25,$9c,$2c
	.byte $85,$92,$0d,$94,$0d,$92,$25,$94,$25,$92,$2b,$94,$2a,$81
_ref116:
	.byte $92,$11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$29,$9c,$3a
	.byte $3c,$83,$84,$29,$29,$8a,$29,$9c,$3b,$92,$29,$94,$28,$81
	.byte $ff,$10
	.word _ref113
_ref118:
	.byte $92,$09,$94,$09,$86,$21,$21,$8c,$20,$85,$86,$21,$8c,$21,$9c,$4a
	.byte $85,$86,$21,$21,$8c,$21,$9c,$47,$92,$21,$94,$20,$81
_ref119:
	.byte $92,$0d,$94,$0d,$86,$25,$25,$8c,$24,$85,$86,$25,$8c,$25,$9c,$4a
	.byte $85,$92,$0d,$94,$0d,$92,$25,$94,$25,$92,$2b,$94,$2a,$81
_ref120:
	.byte $83,$84,$29,$29,$8a,$29,$84,$29,$8a,$29,$84,$29,$29,$a2,$17,$84
	.byte $29,$8a,$28,$85,$84,$29,$29,$a2,$14,$85
_ref121:
	.byte $17,$86,$2f,$2f,$a2,$17,$86,$2f,$8c,$2f,$86,$2f,$2f,$8c,$2e,$85
	.byte $86,$2f,$2f,$a2,$1a,$85,$1e,$85
_ref122:
	.byte $83,$86,$21,$21,$a2,$17,$86,$21,$a2,$17,$86,$21,$21,$8c,$21,$86
	.byte $21,$8c,$20,$85,$86,$21,$21,$a2,$16,$85
_ref123:
	.byte $15,$86,$25,$25,$8c,$25,$86,$25,$a2,$15,$86,$25,$25,$a2,$14,$85
	.byte $86,$25,$25,$96,$28,$2c,$83,$2e,$85
_ref124:
	.byte $2d,$84,$29,$29,$8a,$29,$84,$29,$8a,$29,$84,$29,$29,$a2,$2f,$84
	.byte $29,$8a,$28,$85,$84,$29,$29,$a2,$28,$85
_ref125:
	.byte $2f,$86,$2f,$2f,$8c,$2f,$86,$2f,$8c,$2f,$86,$2f,$2f,$96,$32,$85
	.byte $86,$2f,$2f,$a2,$32,$85,$36,$85
_ref126:
	.byte $83,$86,$21,$21,$a2,$39,$86,$21,$a2,$39,$86,$21,$21,$8c,$21,$86
	.byte $21,$8c,$20,$85,$86,$21,$21,$a2,$36,$38,$83
_ref127:
	.byte $3d,$86,$25,$25,$8c,$25,$86,$25,$a2,$3d,$86,$25,$25,$8c,$24,$85
	.byte $a2,$3c,$95
	.byte $ff,$0b
	.word _ref88
	.byte $ff,$0b
	.word _ref89
	.byte $ff,$09
	.word _ref90
_ref131:
	.byte $97,$2e,$a5
	.byte $ff,$0d
	.word _ref92
_ref133:
	.byte $97,$2c,$a5
	.byte $ff,$08
	.word _ref94
_ref135:
	.byte $97,$46,$a5
	.byte $ff,$0b
	.word _ref96
	.byte $ff,$0b
	.word _ref89
	.byte $ff,$09
	.word _ref90
_ref139:
	.byte $97,$2e,$a5
	.byte $ff,$0e
	.word _ref100
	.byte $ff,$0d
	.word _ref101
_ref142:
	.byte $2e,$bd
_ref143:
	.byte $a4,$14,$16,$bb
	.byte $fd
	.word _song0ch1loop

_song0ch2:
_song0ch2loop:
_ref144:
	.byte $80,$28,$00,$28,$00,$29,$01,$41,$29,$01,$24,$00,$28,$00,$28,$00
	.byte $29,$01,$41,$98,$44,$85,$46,$81
_ref145:
	.byte $80,$2e,$00,$2e,$00,$2f,$01,$47,$2f,$01,$28,$00,$2e,$00,$2e,$00
	.byte $2e,$00,$83,$98,$46,$85,$44,$46,$44,$81
_ref146:
	.byte $80,$20,$00,$20,$00,$21,$01,$39,$21,$01,$1e,$00,$20,$00,$20,$00
	.byte $21,$01,$98,$39,$3a,$85,$3c,$81
_ref147:
	.byte $80,$24,$00,$24,$00,$25,$01,$3d,$25,$01,$22,$00,$25,$01,$98,$3d
	.byte $45,$46,$85,$44,$46,$44,$81
	.byte $ff,$16
	.word _ref144
	.byte $ff,$18
	.word _ref145
_ref150:
	.byte $80,$20,$00,$20,$00,$21,$01,$39,$21,$01,$1e,$00,$20,$00,$20,$00
	.byte $21,$01,$39,$98,$3a,$85,$3c,$81
_ref151:
	.byte $80,$24,$00,$24,$00,$25,$01,$98,$3a,$3c,$83,$44,$46,$45,$3c,$89
	.byte $3a,$36,$80,$25,$01,$3c,$00,$3c,$00
_ref152:
	.byte $28,$00,$28,$00,$29,$01,$41,$00,$85,$24,$00,$28,$00,$28,$00,$29
	.byte $01,$41,$41,$29,$00,$81
_ref153:
	.byte $2e,$00,$2e,$00,$2f,$01,$47,$00,$85,$28,$00,$2e,$00,$2e,$00,$2e
	.byte $00,$83,$47,$01,$46,$00,$46,$00
_ref154:
	.byte $20,$00,$20,$00,$21,$01,$39,$00,$85,$20,$00,$20,$00,$20,$00,$21
	.byte $01,$39,$39,$21,$00,$81
_ref155:
	.byte $24,$00,$24,$00,$25,$01,$3d,$00,$85,$22,$00,$24,$00,$24,$00,$24
	.byte $00,$83,$3c,$83,$00,$25,$3c,$81
	.byte $ff,$16
	.word _ref152
	.byte $ff,$18
	.word _ref153
	.byte $ff,$16
	.word _ref154
_ref159:
	.byte $24,$00,$24,$00,$25,$01,$3d,$00,$85,$23,$24,$85,$3d,$3d,$24,$85
	.byte $37,$36,$81
_ref160:
	.byte $20,$83,$00,$20,$00,$20,$83,$00,$20,$00,$39,$01,$20,$83,$00,$20
	.byte $00,$20,$83,$00,$21,$3a,$85
_ref161:
	.byte $24,$83,$00,$24,$00,$24,$83,$00,$24,$00,$3d,$01,$24,$83,$00,$24
	.byte $00,$24,$83,$00,$24,$00,$44,$85
_ref162:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$83,$00,$2e
	.byte $00,$2e,$83,$00,$2f,$2c,$85
_ref163:
	.byte $28,$83,$00,$28,$00,$28,$83,$00,$28,$00,$41,$01,$28,$83,$00,$28
	.byte $00,$28,$83,$00,$41,$3c,$85
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
_ref167:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$85,$00,$85
	.byte $44,$98,$46,$83,$80,$4a,$85
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
	.byte $ff,$17
	.word _ref163
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
_ref175:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$85,$00,$95
_ref176:
	.byte $28,$00,$28,$00,$29,$01,$41,$29,$01,$24,$00,$28,$00,$28,$00,$29
	.byte $01,$41,$98,$44,$85,$46,$81
	.byte $ff,$18
	.word _ref145
	.byte $ff,$16
	.word _ref146
	.byte $ff,$15
	.word _ref147
	.byte $ff,$16
	.word _ref144
	.byte $ff,$18
	.word _ref145
	.byte $ff,$16
	.word _ref150
	.byte $ff,$16
	.word _ref151
_ref184:
	.byte $28,$00,$29,$9e,$41,$40,$89,$40,$8d,$41,$40,$89,$80,$41,$00,$81
_ref185:
	.byte $28,$00,$29,$9e,$41,$40,$89,$40,$8d,$80,$28,$00,$9e,$29,$80,$40
	.byte $00,$9e,$41,$80,$46,$00,$9e,$46,$81
_ref186:
	.byte $80,$2e,$00,$2f,$9e,$47,$46,$89,$46,$8d,$47,$46,$89,$80,$47,$00
	.byte $81
_ref187:
	.byte $24,$00,$25,$9e,$3d,$3c,$89,$3c,$8d,$80,$24,$00,$9e,$25,$80,$3c
	.byte $00,$9e,$3d,$80,$42,$00,$9e,$42,$81
_ref188:
	.byte $80,$28,$00,$29,$9e,$41,$40,$89,$40,$8d,$41,$40,$89,$80,$41,$00
	.byte $81
	.byte $ff,$12
	.word _ref185
_ref190:
	.byte $80,$20,$00,$21,$9e,$39,$38,$89,$38,$8d,$39,$38,$89,$80,$39,$00
	.byte $81
_ref191:
	.byte $24,$00,$25,$9e,$3d,$3c,$89,$3c,$8d,$80,$24,$00,$24,$89,$00,$85
	.byte $ff,$16
	.word _ref152
	.byte $ff,$18
	.word _ref153
	.byte $ff,$16
	.word _ref154
	.byte $ff,$18
	.word _ref155
	.byte $ff,$16
	.word _ref152
	.byte $ff,$18
	.word _ref153
	.byte $ff,$16
	.word _ref154
	.byte $ff,$13
	.word _ref159
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
	.byte $ff,$17
	.word _ref163
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
	.byte $ff,$15
	.word _ref167
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
	.byte $ff,$17
	.word _ref163
	.byte $ff,$17
	.word _ref160
	.byte $ff,$18
	.word _ref161
	.byte $ff,$17
	.word _ref162
	.byte $ff,$10
	.word _ref175
	.byte $fd
	.word _song0ch2loop

_song0ch3:
	.byte $fb,$06
_song0ch3loop:
_ref216:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05
	.byte $8e,$1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $1f,$fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$90,$1f,$fb,$05,$8e,$1f
	.byte $fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$1e,$81
_ref217:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05,$8e
	.byte $1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$90,$1f,$fb,$05,$8e,$1f,$fb
	.byte $03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$1e,$81
	.byte $ff,$11
	.word _ref217
_ref219:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05,$8e
	.byte $1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83
	.byte $fb,$05,$1f,$fb,$03,$83
	.byte $ff,$11
	.word _ref216
	.byte $ff,$11
	.word _ref217
	.byte $ff,$11
	.word _ref217
	.byte $ff,$10
	.word _ref219
_ref224:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $83,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$90,$1f,$fb
	.byte $03,$83,$fb,$05,$8e,$1f,$fb,$03,$83
_ref225:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $83,$fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f
	.byte $fb,$03,$88,$1f,$fb,$05,$8e,$1f,$fb,$03,$88,$1e,$81
_ref226:
	.byte $fb,$05,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05,$83
	.byte $fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$90,$1f,$fb,$03
	.byte $83,$fb,$05,$8e,$1f,$fb,$03,$83
	.byte $ff,$11
	.word _ref225
	.byte $ff,$10
	.word _ref226
	.byte $ff,$11
	.word _ref225
	.byte $ff,$10
	.word _ref226
_ref231:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $8e,$1f,$fb,$03,$83,$fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$1f,$fb
	.byte $03,$83,$fb,$05,$1f,$fb,$03,$83
_ref232:
	.byte $fb,$05,$8e,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05
	.byte $88,$1f,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb,$05
	.byte $88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1e,$81
_ref233:
	.byte $fb,$05,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05,$88
	.byte $1f,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb,$05,$88
	.byte $1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
_ref239:
	.byte $fb,$05,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05,$90
	.byte $1f,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb,$05,$1b,$fb,$03,$83
	.byte $fb,$05,$83,$fb,$03,$83
	.byte $ff,$11
	.word _ref232
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$10
	.word _ref239
	.byte $ff,$11
	.word _ref216
	.byte $ff,$11
	.word _ref217
	.byte $ff,$11
	.word _ref217
	.byte $ff,$10
	.word _ref219
	.byte $ff,$11
	.word _ref216
	.byte $ff,$11
	.word _ref217
	.byte $ff,$11
	.word _ref217
	.byte $ff,$10
	.word _ref219
_ref256:
	.byte $fb,$05,$90,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb
	.byte $05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03
	.byte $88,$1e,$81
_ref257:
	.byte $fb,$05,$90,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb
	.byte $03,$1e,$81
	.byte $ff,$11
	.word _ref256
	.byte $ff,$11
	.word _ref257
	.byte $ff,$11
	.word _ref256
	.byte $ff,$11
	.word _ref257
	.byte $ff,$11
	.word _ref256
	.byte $ff,$11
	.word _ref257
_ref264:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb
	.byte $03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb,$03,$1f
	.byte $fb,$05,$90,$1f,$fb,$03,$8e,$1e,$81
_ref265:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb,$03
	.byte $1f,$fb,$05,$90,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word _ref265
	.byte $ff,$11
	.word _ref265
	.byte $ff,$11
	.word _ref265
	.byte $ff,$11
	.word _ref265
	.byte $ff,$11
	.word _ref265
_ref271:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$10
	.word _ref239
	.byte $ff,$11
	.word _ref232
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$11
	.word _ref233
	.byte $ff,$10
	.word _ref239
	.byte $fd
	.word _song0ch3loop

_song0ch4:
_song0ch4loop:
_ref288:
	.byte $02,$85,$02,$85,$0b,$02,$85,$03,$03,$03,$02,$85,$0b,$03,$06,$85
_ref289:
	.byte $02,$85,$02,$85,$0b,$02,$85,$03,$03,$03,$02,$85,$0a,$83,$06,$07
	.byte $06,$81
_ref290:
	.byte $02,$85,$02,$85,$0b,$02,$85,$03,$03,$03,$02,$85,$0b,$03,$06,$83
	.byte $06
_ref291:
	.byte $02,$85,$02,$85,$0b,$02,$85,$0b,$02,$83,$06,$0b,$0b,$0a,$83,$06
	.byte $0b,$0a,$81
	.byte $ff,$10
	.word _ref288
	.byte $ff,$12
	.word _ref289
_ref294:
	.byte $02,$85,$02,$85,$0b,$02,$85,$03,$03,$03,$02,$85,$0b,$02,$85,$0a
	.byte $81
_ref295:
	.byte $02,$85,$02,$85,$0b,$02,$85,$03,$0a,$93,$06,$07,$06,$81
_ref296:
	.byte $02,$8d,$06,$89,$02,$89,$02,$85,$07,$02,$89
_ref297:
	.byte $02,$85,$02,$85,$06,$89,$02,$89,$02,$85,$06,$85,$03,$02,$81
_ref298:
	.byte $02,$8d,$06,$89,$02,$89,$02,$85,$07,$02,$85,$06,$81
_ref299:
	.byte $02,$85,$02,$85,$06,$85,$07,$02,$89,$02,$85,$06,$85,$07,$06,$81
	.byte $ff,$0b
	.word _ref296
	.byte $ff,$0f
	.word _ref297
	.byte $ff,$0d
	.word _ref298
_ref303:
	.byte $02,$85,$02,$85,$07,$02,$85,$07,$02,$8b,$06,$0a,$85,$0a,$85
_ref304:
	.byte $02,$89,$03,$06,$89,$02,$89,$02,$85,$0b,$02,$89
_ref305:
	.byte $02,$89,$03,$06,$89,$02,$85,$07,$02,$85,$0a,$85,$03,$02,$81
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
_ref311:
	.byte $02,$89,$03,$06,$89,$02,$85,$07,$02,$83,$0a,$0a,$85,$0a,$85
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
_ref319:
	.byte $02,$89,$03,$06,$89,$02,$85,$07,$02,$85,$0a,$8d
	.byte $ff,$10
	.word _ref288
	.byte $ff,$12
	.word _ref289
	.byte $ff,$11
	.word _ref290
	.byte $ff,$13
	.word _ref291
	.byte $ff,$10
	.word _ref288
	.byte $ff,$12
	.word _ref289
	.byte $ff,$11
	.word _ref294
	.byte $ff,$0e
	.word _ref295
_ref328:
	.byte $02,$8d,$0c,$89,$10,$89,$10,$85,$0c,$89,$10,$81
_ref329:
	.byte $02,$85,$10,$85,$0d,$10,$85,$10,$89,$02,$85,$0d,$02,$89
	.byte $ff,$0c
	.word _ref328
_ref331:
	.byte $02,$85,$10,$85,$0d,$10,$85,$10,$85,$0d,$10,$85,$0c,$85,$0d,$0c
	.byte $81
	.byte $ff,$0c
	.word _ref328
	.byte $ff,$11
	.word _ref331
	.byte $ff,$0c
	.word _ref328
_ref335:
	.byte $02,$85,$10,$85,$0d,$10,$85,$02,$8f,$06,$07,$07,$07,$06,$81
_ref336:
	.byte $02,$89,$03,$07,$02,$85,$06,$89,$02,$85,$0b,$02,$85,$02,$81
_ref337:
	.byte $02,$89,$03,$07,$02,$85,$07,$02,$85,$02,$85,$0b,$03,$02,$85
	.byte $ff,$0f
	.word _ref336
_ref339:
	.byte $02,$89,$03,$07,$02,$85,$07,$02,$85,$02,$85,$0b,$03,$0b,$0a,$81
	.byte $ff,$0f
	.word _ref336
	.byte $ff,$0f
	.word _ref337
	.byte $ff,$0f
	.word _ref336
_ref343:
	.byte $02,$89,$03,$0b,$03,$0b,$0b,$0a,$8d,$06,$83,$06,$07,$06,$81
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref311
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0f
	.word _ref305
	.byte $ff,$0c
	.word _ref304
	.byte $ff,$0c
	.word _ref319
	.byte $fd
	.word _song0ch4loop
.scend